# Generated by Django 6.1 on 2026-09-29 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo único del producto.', max_length=150, unique=True, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Detalles o especificaciones adicionales del producto.', verbose_name='Descripción')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad actual de unidades disponibles en bodega.', verbose_name='Stock disponible')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de venta unitario en CLP.', max_digits=10, verbose_name='Precio unitario')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(help_text='Número de unidades pedidas en la transacción.', verbose_name='Cantidad solicitada')),
                ('stock_previo', models.IntegerField(help_text='Stock en bodega antes de evaluar la transacción.', verbose_name='Stock previo')),
                ('stock_resultante', models.IntegerField(help_text='Stock en bodega después de procesar la solicitud.', verbose_name='Stock resultante')),
                ('estado', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Inválido', 'Inválido')], max_length=20, verbose_name='Estado de la transacción')),
                ('motivo', models.TextField(help_text='Justificación detallada de la aprobación o motivo del rechazo.', verbose_name='Motivo de la resolución')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora de registro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.producto', verbose_name='Producto asociado')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
